# Generated by Django 6.0.4 on 2026-04-21 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField(default=12)),
                ('interest', models.IntegerField(default=0)),
                ('fine', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=30)),
                ('passport_serial', models.CharField(blank=True, max_length=9, null=True)),
                ('passport_pinfl', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('passport_got_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('passport_got_region', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(default='NULLED NAME', max_length=250)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
