# Generated by Django 6.0.4 on 2026-04-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='stir',
            field=models.CharField(default='NONE', max_length=15),
        ),
    ]
