# Generated by Django 6.0.4 on 2026-04-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0004_alter_client_first_name_alter_client_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='income',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
