# Generated by Django 6.0.4 on 2026-04-21 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0005_client_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tangerine.application'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tangerine.client'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pay_day',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
