# Generated by Django 6.0.4 on 2026-04-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0006_contract_amount_contract_application_contract_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
