# Generated by Django 6.0.4 on 2026-04-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0007_contract_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tangerine.shop'),
        ),
    ]
