# Generated by Django 6.0.4 on 2026-04-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0008_contract_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
