# Generated by Django 6.0.4 on 2026-04-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0010_alter_contract_pay_day_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
