# Generated by Django 6.0.4 on 2026-04-25 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0011_phonenumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pay_day',
            field=models.IntegerField(default=25),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tangerine.contract')),
                ('shop', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tangerine.shop')),
            ],
        ),
    ]
