# Generated by Django 6.0.4 on 2026-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0013_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('given', 'Berilgan'), ('rejected', 'Rad etilgan'), ('pending', 'Jarayonda'), ('yopilgan', 'Yopilgan')], default='pending', max_length=30),
        ),
    ]
