# Generated by Django 6.0.4 on 2026-04-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0014_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('given', 'Berilgan'), ('rejected', 'Rad etilgan'), ('pending', 'Jarayonda'), ('closed', 'Yopilgan')], default='pending', max_length=30),
        ),
    ]
