# Generated by Django 6.0.4 on 2026-04-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0015_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
