# Generated by Django 6.0.4 on 2026-05-06 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0017_alter_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pay_day',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tangerine.contract'),
        ),
    ]
