# Generated by Django 6.0.4 on 2026-05-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0018_alter_contract_pay_day_alter_product_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tangerine.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tangerine.contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pay_day',
            field=models.IntegerField(default=7),
        ),
    ]
