# Generated by Django 6.0.4 on 2026-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0019_monthlypayment_client_monthlypayment_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
